In [1]:
import numpy as np
from collections import Counter, OrderedDict, namedtuple

In [2]:
data = np.random.randint(0, 10, [20])
data

array([0, 3, 7, 2, 0, 0, 9, 7, 4, 1, 2, 3, 0, 6, 1, 2, 7, 8, 6, 8])

In [3]:
list(filter(lambda x: x>5, data))

[7, 9, 7, 6, 7, 8, 6, 8]

In [4]:
nums=10
data = {i:j for i,j in zip(np.arange(1, nums+1, 1),np.random.randint(50, 100, [nums]))}
data, len(data)

({1: 72, 2: 60, 3: 51, 4: 51, 5: 78, 6: 80, 7: 83, 8: 56, 9: 52, 10: 73}, 10)

In [5]:
result = {k:v for k,v in data.items() if v > 60}
result, len(result)

({1: 72, 5: 78, 6: 80, 7: 83, 10: 73}, 5)

In [6]:
l = [x for x in range(3)]
l

[0, 1, 2]

In [7]:
np.random.choice(l, 100, p=[0.9, 0, 0.1])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
set(l) ^ set(np.arange(5))

{3, 4}

In [10]:
data_1 = data.copy()
print(data_1)
data_1.update({1:80})
data_1

{1: 72, 2: 60, 3: 51, 4: 51, 5: 78, 6: 80, 7: 83, 8: 56, 9: 52, 10: 73}


{1: 80, 2: 60, 3: 51, 4: 51, 5: 78, 6: 80, 7: 83, 8: 56, 9: 52, 10: 73}

In [11]:
list(map(lambda x: x*10, np.random.randn(3, 3)))

[array([  5.74659898,   4.92826652, -11.56247678]),
 array([ 5.25850397, -0.36473757, 25.07862221]),
 array([-3.85408866, -1.45031063, -8.71656471])]

In [12]:
from functools import reduce

reduce(lambda x, y: x+y, np.random.randn(3,3,3))

array([[-0.26778412,  0.31050085,  0.85657359],
       [-3.49123928, -1.97513778, -2.99245731],
       [-1.03463125, -0.89369099, -2.64643903]])

In [13]:
counter = Counter()
counter.update(np.random.randint(0, 10, 100))
counter.update(np.random.randint(0, 10, 100))
counter.update(np.random.randint(0, 10, 100))
counter.most_common()

[(4, 38),
 (2, 35),
 (9, 32),
 (0, 32),
 (8, 31),
 (7, 28),
 (1, 28),
 (3, 26),
 (6, 26),
 (5, 24)]

In [14]:
counter[1]

28

In [15]:
np.random.choice(10, 10, replace=False)


array([3, 2, 6, 9, 4, 8, 5, 7, 0, 1])

In [16]:
od = OrderedDict()
for k, v in zip(np.random.choice(10, 10, replace=False), np.random.randn(10)):
    od[k] = v
od

OrderedDict([(4, -0.038083854865293545),
             (2, 0.17717061717049978),
             (9, 0.26231591994418796),
             (6, 0.15032132321261346),
             (1, 0.7171240496127479),
             (3, -0.9625855199853354),
             (7, -0.6993530502526601),
             (0, -1.223522778960332),
             (5, -1.8271295356219153),
             (8, 1.1429303596806282)])

In [17]:
od_1 = od.copy()
print(od_1)
od_1.update({1:np.float64(0.5)})
od_1

OrderedDict([(4, -0.038083854865293545), (2, 0.17717061717049978), (9, 0.26231591994418796), (6, 0.15032132321261346), (1, 0.7171240496127479), (3, -0.9625855199853354), (7, -0.6993530502526601), (0, -1.223522778960332), (5, -1.8271295356219153), (8, 1.1429303596806282)])


OrderedDict([(4, -0.038083854865293545),
             (2, 0.17717061717049978),
             (9, 0.26231591994418796),
             (6, 0.15032132321261346),
             (1, 0.5),
             (3, -0.9625855199853354),
             (7, -0.6993530502526601),
             (0, -1.223522778960332),
             (5, -1.8271295356219153),
             (8, 1.1429303596806282)])

In [18]:
help(namedtuple)

Help on function namedtuple in module collections:

namedtuple(typename, field_names, *, rename=False, defaults=None, module=None)
    Returns a new subclass of tuple with named fields.
    
    >>> Point = namedtuple('Point', ['x', 'y'])
    >>> Point.__doc__                   # docstring for the new class
    'Point(x, y)'
    >>> p = Point(11, y=22)             # instantiate with positional args or keywords
    >>> p[0] + p[1]                     # indexable like a plain tuple
    33
    >>> x, y = p                        # unpack like a regular tuple
    >>> x, y
    (11, 22)
    >>> p.x + p.y                       # fields also accessible by name
    33
    >>> d = p._asdict()                 # convert to a dictionary
    >>> d['x']
    11
    >>> Point(**d)                      # convert from a dictionary
    Point(x=11, y=22)
    >>> p._replace(x=100)               # _replace() is like str.replace() but targets named fields
    Point(x=100, y=22)



In [19]:
Users = namedtuple('Users', ['username', 'ac', 'pswd'])
Users

__main__.Users

In [20]:
u1 = Users('li', 'li@126.com', '123456')
u1

Users(username='li', ac='li@126.com', pswd='123456')

In [21]:
u1.username

'li'

In [22]:
u1[0]

'li'

In [23]:
getattr(u1, 'username')

'li'

In [24]:
sorted(
    [
        Users('z', 'z@126.com', '123456'),
        Users('l', 'l@126.com', '123456'),
    ],
    key=lambda x: x.ac
    )

[Users(username='l', ac='l@126.com', pswd='123456'),
 Users(username='z', ac='z@126.com', pswd='123456')]

In [25]:
l.reverse()
l

[2, 1, 0]

In [26]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [27]:
sorted(
    [
        Users('z', 'z@126.com', '123456'),
        Users('l', 'l@126.com', '123456'),
    ],
    key=lambda x: x.ac
    )

[Users(username='l', ac='l@126.com', pswd='123456'),
 Users(username='z', ac='z@126.com', pswd='123456')]

In [28]:
data_1 =  data.copy()
sorted(data_1)
data_1

{1: 72, 2: 60, 3: 51, 4: 51, 5: 78, 6: 80, 7: 83, 8: 56, 9: 52, 10: 73}

In [29]:
sorted(data_1.items(), key=lambda x: x[1], reverse=True)

[(7, 83),
 (6, 80),
 (5, 78),
 (10, 73),
 (1, 72),
 (2, 60),
 (8, 56),
 (9, 52),
 (3, 51),
 (4, 51)]

Help on built-in function fromkeys:

fromkeys(iterable, value=None, /) method of builtins.type instance
    Create a new dictionary with keys from iterable and values set to value.

